readers/urls.py
from django.conf.urls import url
import views
from django.contrib.auth import views as auth_views
app_name = "readers"
urlpatterns = [url(r'^homepage$', views.homepage,name="homepage"),
               url(r'^signupform$',views.signupform,name="signupform"),
               url(r'^signup_reader$',views.signup,{'type_user': 'reader'},name="signup_reader"),
               url(r'^signup_publisher$',views.signup,{"type_user":"publisher"},name="signup_publisher"),
               url(r'^logout$',views.logoutview,name='logout'),
               url(r'^login/$',auth_views.login,{'template_name': "registration/login.html"},name='login'),
               url(r'^genre_books/(?P<genre_id>[0-9]+)/$',views.books_in_genre,name="books_in_genre"),
               url(r'^book_detail/(?P<book_id>[0-9]+)/$',views.book_detail,name="book_detail"),
               url(r'^book_detail/(?P<book_id>[0-9]+)/add_review$',views.add_review,name="add_review"),
               url(r'^home$', views.home, name="home"),
               url(r'^text_review/(?P<book_id>[0-9]+)$', views.TextReviewView.as_view(), name="text_review"),
               url(r'add_book',views.add_book,name="add_book"),
               url(r'^publisher_home$',views.publisher_home,name="publisher_home")
]

untitled1/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^reader/',include("readers.urls"))
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

readers/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.urlresolvers import reverse
from publisher.models import Publisher


class Genre(models.Model):
    genre_name = models.CharField(max_length=30)
    genre_logo = models.ImageField(default="no_image.png")

    def __str__(self):
        return self.genre_name




class MyBook(models.Model):
    isbn = models.IntegerField(editable=True, primary_key=True)
    book_name = models.CharField(max_length=30)
    genre = models.ManyToManyField(Genre)
    synopsis = models.TextField(max_length=500)
    cover = models.ImageField()
    sample = models.FileField(default=None)
    author = models.CharField(max_length=30)
    added_on = models.DateField(auto_now=True)
    published_on = models.DateField(default=None)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)

    def __str__(self):
        return self.book_name + " by " + self.author


class Reader(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favourite_genre = models.ManyToManyField(Genre, blank=True)
    about_reader = models.CharField(max_length=100, blank=True)
    books_read = models.ManyToManyField(MyBook, blank=True, through='ReadingDetails')
    dob = models.DateField(auto_now=True)
    country = models.CharField(max_length=30, blank=True)
    reader_profile_picture = models.FileField(default="no_image.png")

    def __str__(self):
        return self.user.username


class ReadingDetails(models.Model):
    book_read_on = models.DateField(auto_now=True)
    book = models.ForeignKey(MyBook, on_delete=models.CASCADE)
    reader = models.ForeignKey(Reader, on_delete=models.CASCADE)

    def __str__(self):
        return self.book+" read by "+self.reader


class Text_Review(models.Model):
    review = models.TextField(max_length=200)
    reader = models.ForeignKey(Reader,on_delete=models.CASCADE)
    book = models.ForeignKey(MyBook,on_delete=models.CASCADE)
    rating = models.FloatField(validators = [MinValueValidator(0.0), MaxValueValidator(6.0)])
    posting_time = models.TimeField()
    posting_date = models.DateField()

    def __str__(self):
        return "Review posted by "+self.reader.user.username+" on book "+self.book.book_name

    def get_absolute_url(self):
        return reverse("readers:book_detail", kwargs={"book_id": self.book.isbn})



class Video_Review(models.Model):
    reader = models.ForeignKey(Reader, on_delete=models.CASCADE)
    book = models.ForeignKey(MyBook,on_delete=models.CASCADE)
    video = models.FileField()
    youtube_link = models.TextField()
    rating = models.FloatField()

    def __str__(self):
        return "Review posted by"+self.reader+"on book"+self.book

readers/views.py
from django.shortcuts import render, redirect
from models import Genre, MyBook, Reader, Text_Review, Video_Review
from django.core.urlresolvers import reverse_lazy,reverse
from django.contrib.auth.models import User,Permission
from django.contrib.auth import login, logout
from django.http import HttpResponseRedirect, HttpResponse
import re
from django.forms import ModelForm
from django.views.generic import CreateView
import datetime
from publisher.models import Publisher


# Create your views here.
first_name_re = re.compile(r"^[a-zA-Z]{1,30}$")
last_name_re = re.compile(r'^[a-zA-Z]{1,30}$')
username_re = re.compile(r'^[a-zA-Z0-9_-]{3,20}$')
password_re = re.compile(r"^.{3,20}$")
email_re = re.compile(r"^[\S]+@[\S]+.[\S]+$")

def add_book(request):
    try:
        if request.user.publisher:
            return render(request, "readers/add_book_form.html", {})
    except:
            return render(request,"readers/signupform_publisher.html",{})





def add_review(request,book_id):
    current_user = request.user.first_name
    book = MyBook.objects.get(pk=book_id)
    return HttpResponse("Review will be added by :"+current_user+"<br>The Book is"+book.book_name)


def books_in_genre(request, genre_id):
    genre = Genre.objects.get(pk=genre_id)
    books = genre.mybook_set.all()
    return render(request, "readers/book_list.html", {'books': books,
                                                      'genre': genre})


def book_detail(request, book_id):
    book = MyBook.objects.get(pk=book_id)
    try:
        book_reviews = book.text_review_set.all()
    except:
        book_reviews = ""
    try:
        book_review_by_user = request.user.reader.text_review_set.get(book=book)
    except:
         book_review_by_user = ""
    return render(request, "readers/book_detail.html", {'book': book,
                                                        'book_reviews': book_reviews,
                                                        'book_review_by_user': book_review_by_user})


def homepage(request):
    genre = Genre.objects.all()
    return render(request, "readers/homepage.html",{"genre": genre})


def signupform(request):
    return render(request, "readers/Signupform_reader.html", {})


def validate(f, l, e, p, c, pub_name="Reader"):
    error = False
    error_first_name = error_last_name = error_password = error_email =error_pub_name= ""
    if first_name_re.match(str(f).lower()) is None:
        error = True
        error_first_name = "First name not valid!"
    if last_name_re.match(l.lower())is None:
        error = True
        error_last_name = "Last name not valid!"
    if email_re.match(e.lower()) is None:
        error = True
        error_email = "Email Is Required!"
    if password_re.match(p) is None or password_re.match(c) is None or len(p) != len(c):
        error = True
        if len(p) != len(c):
            error_password = "Password Does not Match"
        else:
            error_password = " Invalid password!"
    if pub_name == "":
        error = True
        error_pub_name = "Publication Name required"
    if error:
        return {'error_first_name': error_first_name,
                'error_last_name': error_last_name,
                'error_email': error_email,
                'error_password': error_password,
                'error_pub_name': error_pub_name}
    else:
        return True


def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy("readers:homepage"))

def reader_profile(user,request):
    pass


def signup(request,type_user):
    if request.method == "POST":
        first_name = request.POST.get('firstname').strip()
        last_name = request.POST.get('lastname').strip()
        email = request.POST.get('email').strip()
        password = request.POST.get('password').strip()
        confirmpassword = request.POST.get("confirmpassword").strip()
        if type_user=="publisher":
            publication_name=request.POST.get('publicationname').strip()
            country=request.POST.get('country').strip()
            is_valid = validate(first_name, last_name, email, password, confirmpassword,publication_name)
        else:
            country=""
            publication_name=""
            is_valid=validate(first_name, last_name, email, password, confirmpassword)
        if is_valid !=  True:
            error = is_valid
            if type_user=='reader':
                return render(request, "readers/signupform_reader.html", {'error': error,
                                                                      'first_name': first_name,
                                                                      'last_name': last_name,
                                                                      'email': email})
            if type_user=='publisher':
                return render(request, "readers/signupform_publisher.html", {'error': error,
                                                                          'first_name': first_name,
                                                                          'last_name': last_name,
                                                                          'email': email,
                                                                          'publicationname': publication_name,
                                                                          "country": country})

        if type_user == "reader":
            username = str(first_name)+str(last_name)+'r'
        else:
            username = str(first_name)+ str(last_name)+'p'
        try:
            user = User.objects.create_user(username, password=password, first_name=first_name, last_name=last_name, email=email)
            user.save()
            if type_user == 'reader':
                reader = Reader.objects.create(user=user)
                reader.save()
                login(request, user)
                return HttpResponseRedirect(reverse("readers:home"))
            else:
                publisher = Publisher.objects.create(user=user, publication_name=publication_name, country=country, publisher_name=first_name+" "+last_name)
                publisher.save()
                login(request, user)
                return render(request,"readers/add_book_form.html")




        except Exception:
            user_exist = "User Already Exists !"
            if type_user == 'reader':
                return render(request, "readers/signupform_reader.html", {'user_exists': user_exist,
                                                                          'first_name': first_name,
                                                                          'last_name': last_name,
                                                                          'email': email})
            else:
                return render(request, "readers/signupform_publisher.html",  {'user_exists': user_exist,
                                                                              'first_name': first_name,
                                                                              'last_name': last_name,
                                                                              'email': email,
                                                                              'publicationname': publication_name,
                                                                              'country':country})
    else:
        return render(request, "readers/signupform_reader.html", {})


def home(request):
    reader = request.user.reader
    text_reviews = Text_Review.objects.filter(reader=reader)
    video_reviews = Video_Review.objects.filter(reader=reader)
    return render(request, "readers/home.html", {'reader': reader,
                                                 'text_reviews': text_reviews,
                                                 'video_reviews': video_reviews})


class TextReviewForm(ModelForm):
    class Meta:
        model = Text_Review
        fields = ['review', 'rating']


class TextReviewView(CreateView):
    model = Text_Review
    fields = ['rating', 'review']

    def form_valid(self, form):
        form.instance.reader = self.request.user.reader
        form.instance.book = MyBook.objects.get(pk=self.kwargs['book_id'])
        form.instance.posting_date = datetime.datetime.today().date().__str__()
        form.instance.posting_time = datetime.datetime.now().time().__str__()
        return super(TextReviewView, self).form_valid(form)

def publisher_home(request):
    publisher=request.user.publisher
    published_books=MyBook.objects.filter(publisher=publisher)
    return render(request, "readers/publisher_home.html",{"published_books":published_books})

readers/templates/readers/add_book_form.html
{% extends "readers/base.html" %}
{% block body %}
    <div class="main panel">

    </div>

{% endblock %}

readers/templates/readers/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Griffy" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy|Roboto|slabo+27px|cinzel" rel="stylesheet">
    <link type="text/css" href="{% static "reader/style.css" %}" rel="stylesheet">
    <script type="text/javascript" src="{% static "reader/moreinfo.js" %}"></script>
    <meta charset="UTF-8">
    <title>{% block title %}BookMania{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topnavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="navbar-header">
            <a href="{% url "readers:homepage" %}" class="navbar-brand">BookMania</a>
        </div>
        <div class="collapse navbar-collapse " id="topnavbar">
            <ul class="navbar-nav nav">
                <li class="{% block active_albums %}active{% endblock %}">
                {% if user.is_authenticated and user.reader %}
                    <a href="{% url "readers:home" %}">
                        <span class="glyphicon glyphicon-cd"></span>&nbsp;Home
                    </a>
                    {% elif user.is_authenticated and user.publisher%}
                    <a href="{% url "readers:publisher_home" %}">
                        <span class="glyphicon glyphicon-cd"></span>&nbsp;Home
                    </a>
                {% endif %}
                </li>
            </ul>
            <form action="#" class="navbar-form navbar-left" method="get" role="search">
                <div class="form-group">
                    <label>
                         <input type="text" class="form-control" name="search">&nbsp;
                    </label>
                    <button type="submit" class="btn btn-default">Search!</button>
                </div>
            </form>
            <ul class="navbar-nav nav navbar-right">
                <li>
                    <a href="{% url "readers:add_book" %}">
                       <span class="glyphicon glyphicon-plus"> Add a book</span>
                    </a>
                </li>
                <li class="{% block active_add_album %}{% endblock %}">
                {% if user.is_authenticated%}
                     <a href="{% url "readers:logout" %}" >
                        <span class="glyphicon glyphicon-plus"></span>&nbsp;Logout
                    </a>
                    {% else %}
                    <a href="{% url "readers:signupform" %}">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp;Sign Up
                    </a>
                </li>
                <li>
                    <a href="{% url "readers:login"%}">
                        <span class="glyphicon glyphicon-off"></span>&nbsp;Sign In
                    </a>
                </li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}


</body>
</html>

readers/templates/readers/book_detail.html
    {% extends "readers/base.html" %}
    {% block body %}
        <script  type="text/javascript">
        function moreinfo() {
        element=document.getElementById("moreinfo");
        more=document.getElementById("more");
        if(element.innerHTML=="") {
            element.innerHTML="<b>ISDN:</b> {{ book.isbn }}<br><b>Added on: </b>{{book.added_on}}<br><b>Publisher:</b> {{ book.publisher }}<br><b>Published on:</b> {{ book.published_on }}";
            more.innerHTML="..less"

        }
        else {
            element.innerHTML="";
            more.innerHTML="more.."
        }

    }
        </script>

        <div class="main panel col-lg-10 col-lg-offset-1">
        <div class="row">
        <div class="col-lg-4 col-lg-offset-4 ">
            <center>
             <img src="{{ book.cover.url }}" class="img-circle" height="150px" width="150px"><br>
                <h1>{{ book.book_name }}</h1>
                <h4>{{ book.author }}</h4>
                <h5><b>Rating:</b></h5>
                <h5><b>Overall Rating:</b></h5>
                <div id="moreinfo"></div>
                <a id="more" onclick=moreinfo() >more..</a>

            </center>
        </div>
        </div>
            <div class="row">
                <div class="" >
            <b>About:</b> {{ book.synopsis }}
                </div>
            </div>
        </div>
        <div class="panel col-lg-10 col-lg-offset-1">
        {% if user.is_authenticated and user.reader%}
            {% if book_review_by_user %}
                        <h2>Your Review</h2>
                <table>
                <tr>
                    <td rowspan="3"><img src="{{ book_review_by_user.reader.reader_profile_picture.url}}" alt="Your pic" height="100" width="100" class="img-circle"></td>
                </tr>
                <tr>
                    <th>{{ book_review_by_user.reader.user.first_name }}</th>
                </tr>
                <tr>
                               <td>{{ book_review_by_user.review }}</td>
                </tr>
                </table>
                {% else %}
                <a href="{% url "readers:text_review" book_id=book.isbn %}">Post a Review</a>
            {% endif %}
            {% else %}
                <h3>Sign in or Sign up as a reader to post a Review</h3>
        {% endif %}
        </div>
         <div class="panel col-lg-10 col-lg-offset-1">
        {% if book_reviews %}
        <h3>All Reviews</h3>
        {% for review in book_reviews %}
            <table>
                <tr>
                    <td rowspan="3"><img src="{{ review.reader.reader_profile_picture.url}}" alt="Your pic" height="100" width="100" class="img-circle"></td>
                </tr>
                <tr>
                    <th>{{ review.reader.user.first_name }}</th>
                </tr>
                <tr>
                               <td>{{ review.review }}</td>
                </tr>
            </table>
        {% endfor %}
        {% else %}
            <h4>No Reviews Posted on this book</h4>
        {% endif %}
        </div>
{% endblock %}

readers/templates/readers/book_list.html
{% extends "readers/base.html" %}
{% block body %}
    <div class="main panel">
    {% if books %}
        <h1>Books in {{ genre.genre_name }}</h1>
        <table>
        {% for book in books %}
            <tr>
            <td rowspan="2"><img src="{{ book.cover.url }}" class="img-thumbnail" height="100px" width="100px"></td>
                <td><a href="{% url "readers:book_detail" book.isbn%}">{{ book.book_name }}</a></td>
            </tr>
            <tr><td>{{ book.author }}</td></tr>
        {% endfor %}
        </table>
    {% else %}
    <h1>Sorry no books in this genre :(</h1>
    {% endif %}
    </div>
{% endblock %}

readers/templates/readers/home.html
{% extends "readers/base.html" %}
{% block title %}
Home
{% endblock %}
{% block body %}
    <div class="main panel">
    {% if text_reviews %}
        <h1>Your Reviews</h1>
        {% for review in text_reviews %}
            <br>
            <div class="panel ">
                <a href="{% url "readers:book_detail" review.book.isbn %}"> {{ review.book.book_name }}</a>
                {{ review.review }}
            </div>
        {% endfor %}
    {% else %}
        Welcome {{ reader.user.first_name }}<br>
        <h2>All your posted Reviews will be shown here</h2>
    {% endif %}
    </div>
{% endblock %}

readers/templates/readers/homepage.html
{% extends "readers/base.html" %}
{% block body %}
<div class="panel main col-lg-6 col-md-6 col-sm-6 col-xs-6 col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-xs-offset-1">
    <h1>Genre</h1>
    <div class="row">
        {% for genre_detail in genre %}
            <div class="col-md-4 col-lg-4 col-sm-6 col-xs-12">
                {{ genre_detail.genre_name }}
                <a href="{% url "readers:books_in_genre" genre_detail.id%}">
                    <img src="{{ genre_detail.genre_logo.url }}" class="img-thumbnail genre_logo">
                </a>
            </div>
        {% endfor %}
    </div>
</div>

    <div class="main col-lg-offset-1 col-lg-3 col-md-3 col-sm-3 col-xs-3 col-md-offset-1 col-sm-offset-1 col-xs-offset-1 panel">
    {%  if not user.is_authenticated %}
    <h1>Sign up</h1>
        <form action="{% url "readers:signupform" %}">
            <input type="submit" value="signup" class="btn-primary btn">
        </form>
    {% else %}
        <h1>Welcome {{ user.first_name }}</h1>
        {% endif %}

    </div>

{% endblock %}

readers/templates/readers/publisher_home.html
{% extends "readers/base.html"%}
{% block body %}
    <div class="main panel">
    <h1>Books published by You!</h1>
    <h2>You Joined on {{ user.publisher.joined_on }}</h2>
    {% for book in published_books %}
        <div class="panel main">
                <a href="{% url "readers:book_detail" book.isbn %}"> {{book.book_name }}</a>
                {{book.published_on}}

        </div>

        {% endfor %}
    </div>

{% endblock %}

readers/templates/readers/signupform.html
{% extends "readers/base.html"%}
{% block body %}
    <div class="main panel col-lg-8 col-lg-offset-2 form-group">
    <form action="{% url "readers:signup" %}" method="POST" class="form-controls">
        {% csrf_token %}
        <table class="col-lg-6 col-lg-offset-3">
                <tr>
                <th>
                    <label for="firstname">
                    First Name:
                    </label>
                </th>
                <td><input type="text" name="firstname" id="firstname" value="{{ first_name }}" class="form-control"></td><td class="error-style">{{ error.error_first_name }}{{ user_exists }}</td>
                </tr>
                <tr>
                    <th><label for="lastname">
                            Last Name:
                        </label>
                    </th>
                <td><input type="text"name="lastname" id="lastname" value="{{ last_name }}" class="form-control"></td><td class="error-style">{{ error.error_last_name }}</td>
                </tr>
                <tr>
                    <th><label for="email">
                        Email:
                        </label>
                    </th>
                <td><input type="email"name="email" id="email" value="{{ email }}" class="form-control"></td><td class="error-style">{{ error.error_email }}</td>
                </tr>
                <tr>
                    <th><label for="password">
                        Password:
                        </label>
                    </th>
                <td><input type="password"name="password" id="password" class="form-control"></td><td class="error-style">{{ error.error_password}}</td>
                </tr>
                <tr>
                    <th>
                        <label for="confirmpassword">
                        Confirm Password:
                            </label>
                    </th>
                <td><input type="password" name="confirmpassword" id="confirmpassword" class="form-control"></td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" value="Sign Up" class="btn btn-primary form-control" >
                    </td>
                </tr>

            </table>
                </form>

    </div>

{% endblock %}

readers/templates/readers/signupform_publisher.html
{% extends "readers/base.html"%}
{% block body %}
    <div class="main panel col-lg-8 col-lg-offset-2 form-group">
    <form action="{% url "readers:signup_publisher" %}" method="POST" class="form-controls">
        {% csrf_token %}
        <h1>Sign Up as a publisher to Add a Book</h1>
        <table class="col-lg-6 col-lg-offset-3">
                <tr>
                <th>
                    <label for="firstname">
                    First Name:
                    </label>
                </th>
                <td><input type="text" name="firstname" id="firstname" value="{{ first_name }}" class="form-control"></td><td class="error-style">{{ error.error_first_name }}{{ user_exists }}</td>
                </tr>
                <tr>
                    <th><label for="lastname">
                            Last Name:
                        </label>
                    </th>
                <td><input type="text" name="lastname" id="lastname" value="{{ last_name }}" class="form-control"></td><td class="error-style">{{ error.error_last_name }}</td>
                </tr>
                <tr>
                    <th><label for="email">
                        Email:
                        </label>
                    </th>
                <td><input type="email" name="email" id="email" value="{{ email }}" class="form-control"></td><td class="error-style">{{ error.error_email }}</td>
                </tr>
                <tr>
                    <th><label for="password">
                        Password:
                        </label>
                    </th>
                <td><input type="password" name="password" id="password" class="form-control"></td><td class="error-style">{{ error.error_password}}</td>
                </tr>
                <tr>
                    <th>
                        <label for="confirmpassword">
                        Confirm Password:
                            </label>
                    </th>
                <td><input type="password" name="confirmpassword" id="confirmpassword" class="form-control"></td>
                </tr>

            <tr>
                    <th>
                        <label for="publicationname">
                        Publication Name:
                            </label>
                    </th>
                <td><input type="text" name="publicationname" id="publicationname" class="form-control" value="{{ publicationname }}"></td>
                <td class="error-style">{{ error.error_pub_name}}</td>
            <tr>
                    <th>
                        <label for="country">
                        Country:
                            </label>
                    </th>
                <td><input type="text" name="country" id="country" class="form-control" value="{{ country }}"></td>
                </tr>
                <tr>
                </tr>

                            <tr>
                    <td>
                        <input type="submit" value="Sign Up" class="btn btn-primary form-control" >
                    </td>
                </tr>


            </table>
                </form>

    </div>

{% endblock %}

readers/templates/readers/signupform_reader.html
{% extends "readers/base.html"%}
{% block body %}
    <div class="main panel col-lg-8 col-lg-offset-2 form-group">
    <form action="{% url "readers:signup_reader" %}" method="POST" class="form-controls">
        {% csrf_token %}
        <h1>Sign Up as a Reader</h1>
        <table class="col-lg-6 col-lg-offset-3">
                <tr>
                <th>
                    <label for="firstname">
                    First Name:
                    </label>
                </th>
                <td><input type="text" name="firstname" id="firstname" value="{{ first_name }}" class="form-control"></td><td class="error-style">{{ error.error_first_name }}{{ user_exists }}</td>
                </tr>
                <tr>
                    <th><label for="lastname">
                            Last Name:
                        </label>
                    </th>
                <td><input type="text"name="lastname" id="lastname" value="{{ last_name }}" class="form-control"></td><td class="error-style">{{ error.error_last_name }}</td>
                </tr>
                <tr>
                    <th><label for="email">
                        Email:
                        </label>
                    </th>
                <td><input type="email"name="email" id="email" value="{{ email }}" class="form-control"></td><td class="error-style">{{ error.error_email }}</td>
                </tr>
                <tr>
                    <th><label for="password">
                        Password:
                        </label>
                    </th>
                <td><input type="password"name="password" id="password" class="form-control"></td><td class="error-style">{{ error.error_password}}</td>
                </tr>
                <tr>
                    <th>
                        <label for="confirmpassword">
                        Confirm Password:
                            </label>
                    </th>
                <td><input type="password" name="confirmpassword" id="confirmpassword" class="form-control"></td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" value="Sign Up" class="btn btn-primary form-control" >
                    </td>
                </tr>

            </table>
                </form>

    </div>

{% endblock %}

readers/templates/readers/text_review_form.html
{% extends "readers/base.html"%}
{% load widget_tweaks %}
{% block title %}
    Add  TextReview
{% endblock %}
{% block body %}
    <div class="main panel col-lg-offset-2 col-lg-8 form-group">
        <div class="col-lg-offset-4 col-lg-8">
        <h2>Add Your Review here!</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {% for element in form %}
                <tr>
                    <td>
                        {{ element.label }}
                    </td>
                    <td>
                        {{ element|attr:"class:form-control" }}
                    </td>
                </tr>
              {% endfor %}
          <tr>
              <td>
            <button type="submit" class="btn btn-primary" value="post">Post</button>
              </td>
          </tr>
          </table>
            </form>
        </div>
    </div>
{% endblock %}